# Auto-generated source files
SRCS = \
       webserv/client/Client.cpp \
       webserv/config/AConfig.cpp \
       webserv/config/ConfigManager.cpp \
       webserv/config/directive/ADirective.cpp \
       webserv/config/directive/BoolDirective.cpp \
       webserv/config/directive/DirectiveFactory.cpp \
       webserv/config/directive/DirectiveValue.cpp \
       webserv/config/directive/IntDirective.cpp \
       webserv/config/directive/IntStringDirective.cpp \
       webserv/config/directive/SizeDirective.cpp \
       webserv/config/directive/StringDirective.cpp \
       webserv/config/directive/VectorDirective.cpp \
       webserv/config/GlobalConfig.cpp \
       webserv/config/LocationConfig.cpp \
       webserv/config/ServerConfig.cpp \
       webserv/config/validation/ConfigValidator.cpp \
       webserv/config/validation/directive_rules/AllowedValuesRule.cpp \
       webserv/config/validation/directive_rules/AValidationRule.cpp \
       webserv/config/validation/directive_rules/CgiExtValidationRule.cpp \
       webserv/config/validation/directive_rules/HostValidationRule.cpp \
       webserv/config/validation/directive_rules/PortValidationRule.cpp \
       webserv/config/validation/directive_rules/StatusCodeRule.cpp \
       webserv/config/validation/structural_rules/AStructuralValidationRule.cpp \
       webserv/config/validation/structural_rules/MinimumServerBlocksRule.cpp \
       webserv/config/validation/structural_rules/RequiredDirectivesRule.cpp \
       webserv/config/validation/structural_rules/RequiredLocationBlocksRule.cpp \
       webserv/config/validation/structural_rules/SingleDefaultServerPerPortRule.cpp \
       webserv/config/validation/structural_rules/UniqueDirectiveRule.cpp \
       webserv/config/validation/structural_rules/UniqueServerNamesRule.cpp \
       webserv/config/validation/ValidationEngine.cpp \
       webserv/config/validation/ValidationResult.cpp \
       webserv/handler/AHandler.cpp \
       webserv/handler/CgiEnvironment.cpp \
       webserv/handler/CgiHandler.cpp \
       webserv/handler/CgiProcess.cpp \
       webserv/handler/DeleteHandler.cpp \
       webserv/handler/ErrorHandler.cpp \
       webserv/handler/FileHandler.cpp \
       webserv/handler/MIMETypes.cpp \
       webserv/handler/RedirectHandler.cpp \
       webserv/handler/UploadHandler.cpp \
       webserv/handler/URI.cpp \
       webserv/http/HttpConstants.cpp \
       webserv/http/HttpHeaders.cpp \
       webserv/http/HttpRequest.cpp \
       webserv/http/HttpResponse.cpp \
       webserv/http/RequestValidator.cpp \
       webserv/log/Channel.cpp \
       webserv/log/FileChannel.cpp \
       webserv/log/Log.cpp \
       webserv/log/StdoutChannel.cpp \
       webserv/main.cpp \
       webserv/router/Router.cpp \
       webserv/server/Server.cpp \
       webserv/socket/ASocket.cpp \
       webserv/socket/CgiSocket.cpp \
       webserv/socket/ClientSocket.cpp \
       webserv/socket/ServerSocket.cpp \
       webserv/socket/TimerSocket.cpp \
       webserv/utils/AutoIndex.cpp \
       webserv/utils/FileUtils.cpp \
       webserv/utils/utils.cpp
